[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
statelessratio = "ERNmR8VbsNrrrJtpnuwaLtsd1hkZ9oAhi8XAZbqJtUZZ"

[programs.devnet]
statelessratio = "ERNmR8VbsNrrrJtpnuwaLtsd1hkZ9oAhi8XAZbqJtUZZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
